# Generated by Django 3.0.3 on 2020-10-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField()),
                ('anime_name', models.CharField(max_length=100)),
                ('anime_synonyms', models.CharField(max_length=300)),
                ('anime_type', models.CharField(max_length=50)),
                ('anime_rank', models.IntegerField()),
                ('anime_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('anime_rating', models.CharField(max_length=100)),
                ('anime_thumbnail', models.CharField(max_length=500)),
                ('anime_popularity', models.IntegerField(default=0)),
                ('total_members', models.IntegerField(default=0)),
                ('synopsis', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=200)),
                ('total_episodes', models.IntegerField(default=0)),
                ('duration_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('studio', models.CharField(max_length=200)),
                ('start_season', models.CharField(choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('FALL', 'Fall'), ('SUMMER', 'Summer')], default='WINTER', max_length=9)),
                ('start_year', models.IntegerField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed')], default='RUNNING', max_length=9)),
            ],
        ),
    ]
