# Generated by Django 3.1 on 2020-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20201016_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_rank',
            field=models.IntegerField(default=0),
        ),
    ]
