# Generated by Django 3.1 on 2020-10-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_anime_anime_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
