# Generated by Django 3.1 on 2020-10-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20201017_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_rank',
            field=models.CharField(default='Missing', max_length=8),
        ),
    ]
