# Generated by Django 3.1 on 2020-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20201017_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_score',
            field=models.CharField(default='Missing', max_length=5),
        ),
        migrations.AlterField(
            model_name='anime',
            name='duration_min',
            field=models.CharField(default='Missing', max_length=8),
        ),
    ]
