# Generated by Django 3.1 on 2020-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20201017_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='id',
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
