# Generated by Django 3.1 on 2020-10-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20201017_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_rank',
            field=models.IntegerField(default=0),
        ),
    ]
